import type { Metadata } from "next";
import "./globals.css";
import IntroAudioShell from "./intro-audio-shell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <IntroAudioShell>{children}</IntroAudioShell>
      </body>
    </html>
  );
}
